# Game Design Document (GDD) Workflow
name: gdd
description: "Game Design Document workflow for all game project levels - from small prototypes to full AAA games. Generates comprehensive GDD with game mechanics, systems, progression, and implementation guidance."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/2-plan-workflows/gdd"
instructions: "{installed_path}/instructions-gdd.md"
template: "{installed_path}/gdd-template.md"
game_types_csv: "{installed_path}/game-types.csv"

# Output configuration
default_output_file: "{output_folder}/GDD.md"

# Game type references (loaded based on game type selection)
game_type_guides: "{installed_path}/game-types/"

# Recommended input documents
recommended_inputs:
  - game_brief: "{output_folder}/game-brief.md"
  - narrative_design: "{output_folder}/narrative-design.md"
  - market_research: "{output_folder}/market-research.md"

standalone: true
