description = "Executes the Validate Workflow task from the BMad Method."
prompt = """
Execute the following BMad Method task workflow:

@../gemini-workspace/manifesto/bmad/core/tasks/validate-workflow.xml

Follow all instructions and complete the task as defined.
"""
